# Generated by Django 4.2 on 2023-04-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_customer_location_remove_employee_dept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='prefferred_shopping_category',
            new_name='preffered_shopping_category',
        ),
    ]
